version: "3.3"

services:
    spaceship-staking_db:
        image: tokend/postgres-ubuntu:9.6
        restart: unless-stopped
        environment:
           - POSTGRES_USER=spaceship
           - POSTGRES_PASSWORD=spaceship
           - POSTGRES_DB=spaceship
           - PGDATA=/pgdata
        volumes:
           - spaceship-staking-data:/pgdata

    spaceship-staking:
         image: spaceship-staking:latest
         restart: unless-stopped
         environment:
           - KV_VIPER_FILE=/spaceship-staking.yaml
           - CONTRACT_ADDRESS
           - FROM_BLOCK_NUM
           - RPC_END_POINT
           - MISSION_CREATED_HASH=0x280fd1c13afdf05ef9c7dbd512eed44cfa4545e4c471c2673baf1d275a3d8fd9
           - MISSION_JOINED_HASH=0xceb49b5adb5e3737df9e0679d210f1006878fb83bf58974f7279b0c79460898b
           - REWARD_WITHDRAWN_HASH=0x3f0d190fee71fcedf315c1a691ca936a8893467ce62d0bb52e5643ded084fe46
           - DB_URL
           - LOG_LEVEL
           - LOG_DISABLE_SENTRY
         ports:
           - 8279:79
         volumes:
           - ./configs/spaceship-staking.yaml:/spaceship-staking.yaml
         depends_on:
           - spaceship-staking_db
         entrypoint: sh -c "missions-api migrate up && missions-api run service"

    spaceship-staking_api:
         image: spaceship-staking:latest
         restart: unless-stopped
         environment:
           - KV_VIPER_FILE=/spaceship-staking.yaml
           - LISTEN_ADDRESS=:${LISTEN_PORT}
           - DB_URL
           - LOG_LEVEL
           - LOG_DISABLE_SENTRY
         ports:
           - ${EXPOSED_PORT}:${LISTEN_PORT}
         volumes:
           - ./configs/spaceship-staking.yaml:/spaceship-staking.yaml
         depends_on:
           - spaceship-staking_db
         entrypoint: sh -c "missions-api run api"

volumes:
    spaceship-staking-data:
