log:
  level: info
  disable_sentry: true

db:
  url: postgres://spaceship:spaceship@spaceship-staking_db/spaceship?sslmode=disable

rpc:
  endpoint: "https://bsc-dataseed.binance.org/"

contract:
  address: "0x0000000000000000000000000000000000000000"

events:
  mission_joined_hash: "0xceb49b5adb5e3737df9e0679d210f1006878fb83bf58974f7279b0c79460898b"
  mission_created_hash: "0x280fd1c13afdf05ef9c7dbd512eed44cfa4545e4c471c2673baf1d275a3d8fd9"
  reward_withdrawn_hash: "0x7500c4319132adbe5ee377dbd33a4a90bfe57b88551d814b444a80a6c4c6cfa0"


listener:
  addr: :8108

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: bsc-checker-events
  service_port: 80
