// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "d99dcc2bc6ac8ff4b88d9e3b370d104c"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"b0598d1874310428b69df8b40897dfec": "1f8b08000000000000ff8c92df6e83201487ef798a73d966eb13f40af5d490396c9066f18a68642ba98a5116f7f8cb524d71eb9f7109dff9f171389b0d3c35e6a32f9c8643474828904a04498304417f75b5ed75af1a330cc6b6644500e0cfb63215042c665c428c1c059518014dde689e01cd8045c82593f9f3a218bc3515034f25f043929cc9291d1e93a371c7aa2f469f0dacad75d1fe22dbcfa6d4bd1a8ea61bee673aeb8a5a0dae3869e5eae69f64d99677c8bd60af54e4f08239acae74717dc6c2946752d09f80f7939a3932fbee52812ce6cb9435f1db247087027988d9a5df970b4db5a4530e1126281132f475971ef30c5cd5980e6f5acc7fb9f21efbc081acb784f8e319d9b1252412e9fec6786ebf030000ffffb34f7bafcd020000",
		"f2a1046840db4722abb796374cc13ada": "1f8b08000000000000ff8cd2cf6af3300c00f0bb9f42c786ef2b74839e7a4adbb08575696792414fc6b3bdd6acb18dad10faf6234bd33f8379d34df0b3842c8dc7f0afd63bcf5141e50859d02c2d3328d3f92a835a87a0ad2123020043c6b4ec3298e70f79514255e42f55f6ff4b481584d70eb5355dfa9ad2c5634a47f7d369d203c36b059718c0dd649240b12ea1a856ab5ebe59eea5363b86ba7b726ad6c7ad3cf0c688fdc945a532f2cce252369e0f53c4e5f02978742a2ebd6ab997e7d92332382e54d86bc7840df897eeceb6ca476ba2457e605dd1f04b77f38e4c58839e0bec167144c5e14789f64319d6787db5ee49f25d6e68fe9cd22d3c655b185dee2821c98c90eb135cdad610b2a4ebcded09ce3e030000ffff88294f84a8020000",
		"fa4f20dc81dc0dbc06040492ac40a186": "1f8b08000000000000ff6ccfcd6ac3301004e0fb3ec51c13da3c414e4ab5045155499515ad4e46c1a2843ab69105ede397525cdc9fe3c0b7eccc66839bebe5a5a49a1146a23bcf4a18a2769691dfc76e28b9d08a007cc7e6d27ec69dd91b27d8b363af8435947d52f1047582d1ecc448bcfd7997dab6e46982f0b3c01d042e588be0cc63e02f5a879aba66aae93537b5bbce3f66fb179dfbf3ffe8e8cd83f211f71cb15a345fd37a4bb49cad87b79e48fbc3f1d7eced47000000fffff57c787b1d010000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("migrations", "./migrations")
		b.SetResolver("001_mission.sql", packr.Pointer{ForwardBox: gk, ForwardPath: "f2a1046840db4722abb796374cc13ada"})
		b.SetResolver("002_explorer.sql", packr.Pointer{ForwardBox: gk, ForwardPath: "fa4f20dc81dc0dbc06040492ac40a186"})
		b.SetResolver("003_explorer_mission.sql", packr.Pointer{ForwardBox: gk, ForwardPath: "b0598d1874310428b69df8b40897dfec"})
	}()
	return nil
}()
